import { typeid } from "typeid-js";

export const createId = {
	artist: () => typeid("ar").toString(),
	artistAlias: () => typeid("aa").toString(),
	circle: () => typeid("ci").toString(),
	circleLink: () => typeid("cl").toString(),
	track: () => typeid("tr").toString(),
	trackCredit: () => typeid("tc").toString(),
	trackOfficialSong: () => typeid("to").toString(),
	trackDerivation: () => typeid("td").toString(),
	trackPublication: () => typeid("tp").toString(),
	trackIsrc: () => typeid("ti").toString(),
	release: () => typeid("re").toString(),
	releasePublication: () => typeid("rp").toString(),
	releaseJanCode: () => typeid("rj").toString(),
	disc: () => typeid("di").toString(),
	eventSeries: () => typeid("es").toString(),
	event: () => typeid("ev").toString(),
	eventDay: () => typeid("ed").toString(),
	officialWorkLink: () => typeid("wl").toString(),
	officialSongLink: () => typeid("sl").toString(),
	tag: () => typeid("tag").toString(),
	albumRequest: () => typeid("aq").toString(),
	userCollection: () => typeid("uc").toString(),
	userCollectionItem: () => typeid("uci").toString(),
} as const;
